name: Create Issue on Failure
description: Creates an issue when a step/job fails

inputs:
  token:
    description: GitHub token
    required: true
    type: string
  
  run_id:
    description: The run ID of the failed workflow
    required: true
    type: string

  event_name:
    description: The event name that triggered the workflow
    required: true
    type: string
  
  time:
    description: The time of the failure
    required: true
    type: string

  workflow:
    description: The name of the workflow that failed
    required: true
    type: string

  workflow_ref:
    description: The path to the workflow file that failed
    required: true
    type: string
  
  actor:
    description: The original actor that triggered the workflow
    required: true
    type: string

  triggering_actor:
    description: The most recent actor that triggered the workflow
    required: true
    type: string

  repository:
    description: The repository where the workflow is located
    required: true
    type: string

  ref:
    description: The branch or tag that the workflow was triggered on
    required: true
    type: string

  sha:
    description: The commit SHA that the workflow was triggered on
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Create Issue
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ inputs.token }}
        title: |
          [${{ inputs.workflow }}] failed during [${{ inputs.event_name }}] at [OH local time ${{ inputs.time }}]
        assignees: KemingHe,${{ inputs.actor }},${{ inputs.triggering_actor }}
        labels: CICD
        body: |
          ## Failure Report:
          
          > [!IMPORTANT]
          > Details on failed run: https://github.com/${{ inputs.repository }}/actions/runs/${{ inputs.run_id }}

          - Author: ${{ inputs.triggering_actor }}
          - Branch: ${{ inputs.ref }}
          - Commit: ${{ inputs.sha }}
          - Workflow Path: `${{ inputs.workflow_ref }}`

          - [ ] **Task**: Review failed run, fix the issue(s), and re-run until successful.

          > This issue was created automatically by GitHub, 
          > through `dacbd/create-issue-action@main` action and @KemingHe's workflow.
          > Please do not close this issue until the issue is resolved.
          > If you have any questions, please contact @KemingHe.
