# ./.github/workflow/auto-issue-legacy.yml
#
# Legacy method of auto-generating issues when other workflow fails.

name: Legacy Issue

on:
  workflow_run:
    workflows:
      - '*'
    types:
     - 'completed'

permissions:
  contents: read
  issues: write

jobs:
  auto-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout yml
        uses: actions/checkout@v4
      - name: Legacy create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: './.github/issue-templates/legacy-template.md'
          update_existing: true
          search_existing: all
          
