# ./.github/workflows/always-pass.yml
#
# Reusable workflow that always passes when called.
name: Always Pass Workflow

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  succeed:
    runs-on: ubuntu-latest
    steps:
      - name: Succeed and exit
        run: exit 0
        
