# ./.github/workflows/always-fail.yml
#
# A workflow that always fails when ran,
# for testing auto-issue.
name: Always Fail Workflow

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail and exit
        run: exit 1
