# ./.github/workflow/auto-issue-legacy.yml
#
# Legacy method of auto-generating issues when other workflow fails.

name: Legacy Issue

on:
  workflow_run:
    workflows:
      - '*'
    types:
     - 'completed'

permissions:
  contents: read
  issues: write

jobs:
  auto-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout yml
        uses: actions/checkout@v4
      - uses: dacbd/create-issue-action@v2.0.0
        with: 
          title: 'Test new legacy title'
          token: ${{ secrets.GITHUB_TOKEN }}
