# ./.github/workflow/auto-issue-legacy.yml
#
# Legacy method of auto-generating issues when other workflow fails.

name: Legacy Issue

on:
  workflow_run:
    workflows:
      - '*'
    types:
     - 'completed'

permissions:
  contents: read
  issues: write

jobs:
  auto-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout yml
        uses: actions/checkout@v4
        # Added auto-retry feature as fail-safe
        # to unexpected rate-limit issue.
      - uses: dacbd/create-issue-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          title: 'Test new legacy title'
