# ./.github/workflows/common-child-pass.yml
#
# A reusable workflow that always passes.
name: Always-pass Workflow

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  succeed:
    runs-on: ubuntu-latest
    steps:
      - name: Succeed and exit
        run: exit 0
        
