# ./.github/workflows/create-issue-parent.yml
#
# Parent workflow that creates an issue when
# called reusable workflow fails.

name: Parent Workflow

on:
  [push, pull_request]
  
permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  fail-job:
    uses: ./.github/workflows/common-child-fail.yml    

  report-when-fail:
    needs: fail-job
    runs-on: ubuntu-latest
    if: always() && needs.fail-job.result == 'failure'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get event time
        id: event-time
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "time=$(TZ='America/New_York' date -u +'%m/%d %H:%M:%S')" >> "$GITHUB_OUTPUT"
          else
            echo "time=$(TZ='America/New_York' date -d '${{ github.event.pull_request.updated_at }}' +'%m/%d %H:%M:%S')" >> "$GITHUB_OUTPUT"
          fi

      - name: Report status
        id: report-status
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            [${{ github.workflow }}] failed on ${{ github.event_name }} at ${{ steps.event-time.outputs.time }}
          assignees: ${{ github.actor }}
          labels: codeql
          body: |
            ### Failure Report:
            
            > Failed run link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - **Author:** ${{ github.actor }}
            - **Branch:** ${{ github.ref }}
            - **Commit:** ${{ github.sha }}
