# ./.github/workflows/create-issue-parent.yml
#
# Parent workflow that creates an issue when
# called reusable workflow fails.

name: Parent Workflow

on:
  [push, pull_request]
  
permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  test-success-no-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: exit 0
      - name: Report status when fail
        id: report-step
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action failed on PR ${{ github.event.number }}
          assignees: ${{ github.actor }}
          labels: codeql
          body: |
            ### Failure Report:
            
            > Failed run link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - **Author:** ${{ github.actor }}
            - **Branch:** ${{ github.ref }}
            - **Commit:** ${{ github.sha }}
            
  test-failure-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: exit 1
      - name: Report status when fail
        id: report-step
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action failed on PR ${{ github.event.number }}
          assignees: ${{ github.actor }}
          labels: codeql
          body: |
            ### Failure Report:
            
            > Failed run link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - **Author:** ${{ github.actor }}
            - **Branch:** ${{ github.ref }}
            - **Commit:** ${{ github.sha }}
