# ./.github/workflows/test-parent-workflow.yml
#
# Parent workflow to test calling local reusable workflows.
name: Test Parent Workflow

on:
 [push, pull_request]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/always-pass.yml
