# ./.github/workflows/create-issue-parent.yml
#
# Parent workflow that creates an issue when
# called reusable workflow fails.

name: Parent Workflow

on:
  [push, pull_request]
  
permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  fail-job:
    uses: ./.github/workflows/common-child-fail.yml    

  report-when-fail:
    needs: fail-job
    runs-on: ubuntu-latest
    if: always() && needs.fail-job.result == 'failure'
    steps:
      - uses: actions/checkout@v4
      - name: Report status when fail
        id: report-step
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            Workflow ${{ github.workflow }} failed on ${{ github.event_name }} on $(date +'%Y-%m-%d')
          assignees: ${{ github.actor }}
          labels: codeql
          body: |
            ### Failure Report:
            
            > Failed run link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - **Author:** ${{ github.actor }}
            - **Branch:** ${{ github.ref }}
            - **Commit:** ${{ github.sha }}
