# ./.github/workflows/create-issue-parent.yml
#
# Parent workflow that creates an issue when
# called reusable workflow fails.

name: Parent Workflow

on:
  [push, pull_request]
  
permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  fail-job:
    uses: ./.github/workflows/common-child-fail.yml    

  report-when-fail:
    needs: fail-job
    runs-on: ubuntu-latest
    if: always() && needs.fail-job.result == 'failure'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call create issue on failure action
        uses: ./.github/actions/create-issue-on-failure
        with:
          github_context: ${{ toJson(github) }}
